export const UPDATE_LETTERS = 'UPDATE_LETTERS'
export const LOAD_LETTERS = 'LOAD_LETTERS'
export const LETTERS_SUCCESS = 'LETTERS_SUCCESS'
export const LETTERS_FAILURE = 'LETTERS_FAILURE'

export const LOAD_MY_FIRST_LETTERS = 'LOAD_MY_FIRST_LETTERS'
export const LOAD_MY_FIRST_LETTERS_SUCCESS = 'LOAD_MY_FIRST_LETTERS_SUCCESS'
export const LOAD_MY_FIRST_LETTERS_FAILURE = 'LOAD_MY_FIRST_LETTERS_FAILURE'

export const LOAD_FIRST_LETTERS_REPLIED = 'LOAD_FIRST_LETTERS_REPLIED'
export const LOAD_FIRST_LETTERS_REPLIED_SUCCESS = 'LOAD_FIRST_LETTERS_REPLIED_SUCCESS'
export const LOAD_FIRST_LETTERS_REPLIED_FAILURE = 'LOAD_FIRST_LETTERS_REPLIED_FAILURE'

export const LOAD_DETAIL_OF_FIRST_LETTER_REPLIED = 'LOAD_DETAIL_OF_FIRST_LETTER_REPLIED'
export const LOAD_DETAIL_OF_FIRST_LETTER_REPLIED_SUCCESS = 'LOAD_DETAIL_OF_FIRST_LETTER_REPLIED_SUCCESS'

export const CLEAR_LETTERS = 'CLEAR_LETTERS'

export const REPLY = 'REPLY'
export const REPLY_SUCCESS = 'REPLY_SUCCESS'
export const REPLY_FAILURE = 'REPLY_FAILURE'
export const SEND = 'SEND'
export const SEND_SUCCESS = 'SEND_SUCCESS'
export const SEND_FAILURE = 'SEND_FAILURE'

export const CHANGE_LETTER_BOX_PAGE = 'CHANGE_LETTER_BOX_PAGE'
export const PREPARE_REPLY_TO_ME = 'PREPARE_REPLY_TO_ME'
export const PREPARE_REPORT = 'PREPARE_REPORT'
export const PREPARE_RECOMMEND = 'PREPARE_RECOMMEND'
export const RECOMMEND_REQUEST = 'RECOMMEND_REQUEST'
export const RECOMMEND_SUCCESS = 'RECOMMEND_SUCCESS'
export const RECOMMEND_FAILURE = 'RECOMMEND_FAILURE'
export const CHANGE_UNREAD = 'CHANGE_UNREAD'