export const UPDATE_LETTERS = 'UPDATE_LETTERS'
export const LOAD_LETTERS = 'LOAD_LETTERS'
export const LETTERS_SUCCESS = 'LETTERS_SUCCESS'
export const LETTERS_FAILURE = 'LETTERS_FAILURE'

export const LOAD_MY_FIRST_LETTERS = 'LOAD_MY_FIRST_LETTERS'
export const LOAD_MY_FIRST_LETTERS_SUCCESS = 'LOAD_MY_FIRST_LETTERS_SUCCESS'
export const LOAD_MY_FIRST_LETTERS_FAILURE = 'LOAD_MY_FIRST_LETTERS_FAILURE'

export const LOAD_FIRST_LETTERS_REPLIED = 'LOAD_FIRST_LETTERS_REPLIED'
export const LOAD_FIRST_LETTERS_REPLIED_SUCCESS = 'LOAD_FIRST_LETTERS_REPLIED_SUCCESS'
export const LOAD_FIRST_LETTERS_REPLIED_FAILURE = 'LOAD_FIRST_LETTERS_REPLIED_FAILURE'

export const LOAD_CONVERSATIONS_STARTED = 'LOAD_CONVERSATIONS_STARTED'
export const CONVERSATION_STARTED_SUCCESS = 'CONVERSATION_STARTED_SUCCESS'
export const CONVERSATION_STARTED_FAILURE = 'CONVERSATION_STARTED_FAILURE'

export const LOAD_CONVERSATIONS_REPLIED = 'LOAD_CONVERSATIONS_REPLIED'
export const CONVERSATION_REPLIED_SUCCESS = 'CONVERSATION_REPLIED_SUCCESS'
export const CONVERSATION_REPLIED_FAILURE = 'CONVERSATION_REPLIED_FAILURE'