export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const REGISTER = 'REGISTER'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILURE = 'REGISTER_FAILURE'

export const LOAD_USER_INFO = 'LOAD_USER_INFO'
export const LOAD_USER_INFO_SUCCESS = 'LOAD_USER_INFO_SUCCESS'
export const LOAD_USER_INFO_FAILURE = 'LOAD_USER_INFO_FAILURE'
export const RELOAD_USER_INFO = 'RELOAD_USER_INFO'

export const UPDATE_USER_SETTING = 'UPDATE_USER_SETTING'
export const UPDATE_USER_SETTING_SUCCESS = 'UPDATE_USER_SETTING_SUCCESS'
export const UPDATE_USER_SETTING_FAILURE = 'UPDATE_USER_SETTING_FAILURE'