package com.kaixiang.finalproject.dataobject;

import java.util.Date;

public class UserDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id
     *
     * @mbg.generated Tue Jun 22 23:17:13 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.username
     *
     * @mbg.generated Tue Jun 22 23:17:13 CST 2021
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.email
     *
     * @mbg.generated Tue Jun 22 23:17:13 CST 2021
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.stamp
     *
     * @mbg.generated Tue Jun 22 23:17:13 CST 2021
     */
    private Integer stamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.last_login_at
     *
     * @mbg.generated Tue Jun 22 23:17:13 CST 2021
     */
    private Date lastLoginAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.continuous_login_days
     *
     * @mbg.generated Tue Jun 22 23:17:13 CST 2021
     */
    private Integer continuousLoginDays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.status
     *
     * @mbg.generated Tue Jun 22 23:17:13 CST 2021
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.role
     *
     * @mbg.generated Tue Jun 22 23:17:13 CST 2021
     */
    private String role;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.id
     *
     * @return the value of user_info.id
     *
     * @mbg.generated Tue Jun 22 23:17:13 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.id
     *
     * @param id the value for user_info.id
     *
     * @mbg.generated Tue Jun 22 23:17:13 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.username
     *
     * @return the value of user_info.username
     *
     * @mbg.generated Tue Jun 22 23:17:13 CST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.username
     *
     * @param username the value for user_info.username
     *
     * @mbg.generated Tue Jun 22 23:17:13 CST 2021
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.email
     *
     * @return the value of user_info.email
     *
     * @mbg.generated Tue Jun 22 23:17:13 CST 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.email
     *
     * @param email the value for user_info.email
     *
     * @mbg.generated Tue Jun 22 23:17:13 CST 2021
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.stamp
     *
     * @return the value of user_info.stamp
     *
     * @mbg.generated Tue Jun 22 23:17:13 CST 2021
     */
    public Integer getStamp() {
        return stamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.stamp
     *
     * @param stamp the value for user_info.stamp
     *
     * @mbg.generated Tue Jun 22 23:17:13 CST 2021
     */
    public void setStamp(Integer stamp) {
        this.stamp = stamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.last_login_at
     *
     * @return the value of user_info.last_login_at
     *
     * @mbg.generated Tue Jun 22 23:17:13 CST 2021
     */
    public Date getLastLoginAt() {
        return lastLoginAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.last_login_at
     *
     * @param lastLoginAt the value for user_info.last_login_at
     *
     * @mbg.generated Tue Jun 22 23:17:13 CST 2021
     */
    public void setLastLoginAt(Date lastLoginAt) {
        this.lastLoginAt = lastLoginAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.continuous_login_days
     *
     * @return the value of user_info.continuous_login_days
     *
     * @mbg.generated Tue Jun 22 23:17:13 CST 2021
     */
    public Integer getContinuousLoginDays() {
        return continuousLoginDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.continuous_login_days
     *
     * @param continuousLoginDays the value for user_info.continuous_login_days
     *
     * @mbg.generated Tue Jun 22 23:17:13 CST 2021
     */
    public void setContinuousLoginDays(Integer continuousLoginDays) {
        this.continuousLoginDays = continuousLoginDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.status
     *
     * @return the value of user_info.status
     *
     * @mbg.generated Tue Jun 22 23:17:13 CST 2021
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.status
     *
     * @param status the value for user_info.status
     *
     * @mbg.generated Tue Jun 22 23:17:13 CST 2021
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.role
     *
     * @return the value of user_info.role
     *
     * @mbg.generated Tue Jun 22 23:17:13 CST 2021
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.role
     *
     * @param role the value for user_info.role
     *
     * @mbg.generated Tue Jun 22 23:17:13 CST 2021
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }
}